version: '3.8'

services:
  # Backend service
  backend:
    build: ./backend
    container_name: renewable-energy-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - backend_data:/app/models/saved_models
    environment:
      - FLASK_ENV=development
      - PORT=5000
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # Frontend service
  frontend:
    build: ./frontend
    container_name: renewable-energy-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000/api
    restart: unless-stopped
    networks:
      - app-network

# Volumes for persistent data
volumes:
  backend_data:

# Network for communication between containers
networks:
  app-network:
    driver: bridge 